export type Tags =
  | "C"
  | "C++"
  | "Java"
  | "JavaScript"
  | "TypeScript"
  | "Python"
  | "Node.js"
  | "HTML"
  | "CSS"
  | "React"
  | "Next.js"
  | "TailwindCSS"
  | "Framer Motion"
  | "Figma"
  | "Express"
  | "Recoil"
  | "WebSockets"
  | "MongoDB"
  | "PostgreSQL"
  | "MySQL"
  | "Prisma"
  | "Git"
  | "GitHub"
  | "Vercel"
  | "Google OAuth 2.0"
  | "NextAuth.js"
  | "REST APIs"
  | "OneStop"
  | "shadcn"
  | "Radix UI"
  | "Zod"
  | "tRPC"
  | "React Query"
  | "Axios"
  | "Supabase"
  | "Stripe"
  | "Tailwind Variants"
  | "Headless UI"
  | "Resend"
  | "Gemini AI"
  | "OpenAI API"
  | "LangChain"
  | "AI Integration"
  | "Chatbot"
  | "AI Email Automation"
  | "Web Scraping"
  | "Puppeteer"
  | "Playwright"
  | "Cheerio"
  | "BeautifulSoup"
  | "Selenium";
